### ISSUE TITLE
error checking deps

### ISSUE THREAD

**Issue by sigmaSd** [hasundue/deno-molt#19]
a.ts
```ts
import {} from "https://deno.land/std@0.171.0/testing/asserts.ts";
```
deno.json 
```json
{
  "imports": {
    "@/": "./"
  }
}
```

`molt check a.ts` errors with
```
🔎 Checking for updates...
error: Uncaught (in promise) TypeError: Unexpected URI protocol: https:
      throw new TypeError(`Unexpected URI protocol: ${url.protocol}`);
            ^
    at file:///home/mrcool/dev/others/deno-molt/lib/uri.ts:49:13
    at Object.resolve (file:///home/mrcool/dev/others/deno-molt/src/import_map.ts:56:20)
    at _create (file:///home/mrcool/dev/others/deno-molt/src/update.ts:124:38)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///home/mrcool/dev/others/deno-molt/src/update.ts:89:24
    at async Promise.all (index 0)
    at async Object.collect (file:///home/mrcool/dev/others/deno-molt/src/update.ts:86:3)
    at async Command.checkAction [as actionHandler] (file:///home/mrcool/dev/others/deno-molt/cli.ts:23:19)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
```

**Comment by hasundue** [comment]
Thanks for reporting @sigmaSd !
