### ISSUE TITLE
error updating importMap

### ISSUE THREAD

**Issue by sigmaSd** [hasundue/deno-molt#26]
a.ts
```ts
import {} from "a";
```
deno.json
```json
{
  "importMap": "a.json"
}
```
a.json
```json
{
  "imports":{
    "a":"https://deno.land/x/dax@0.17.0/mod.ts"
  }
}
```

molt check a.ts fails with
```
🔎 Checking for updates...
error: Uncaught (in promise) Error: The dependency a in a.ts has no resolved specifier.
    throw new Error(
          ^
    at _create (file:///home/mrcool/dev/others/deno-molt/src/update.ts:113:11)
    at file:///home/mrcool/dev/others/deno-molt/src/update.ts:91:32
    at Array.map (<anonymous>)
    at file:///home/mrcool/dev/others/deno-molt/src/update.ts:90:30
    at Array.flatMap (<anonymous>)
    at Object.collect (file:///home/mrcool/dev/others/deno-molt/src/update.ts:89:21)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.checkAction [as actionHandler] (file:///home/mrcool/dev/others/deno-molt/cli.ts:24:19)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
```

**Comment by hasundue** [comment]
Didn't tested this case. Thanks for pointing it out.
